pytorch中所有神经网络的核心是autograd包。
autograd包为张量上的所有操作提供了自动求导。它是一个在运行时定义的框架，这意味着反向传播是根据所写的代码来确定如何运行，并且每次迭代可以是不同的。

In [1]:
import torch

In [2]:
#创建一个张量并设置requires_grad=True用来追踪他的计算历史
x = torch.ones(2,2,requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [4]:
#对张量进行操作
y = x + 2
print(y)
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [6]:
z = y * y * 3
out = z.mean()
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [7]:
#.requires_grad_()可以改变现有张量的requires_grad属性，若无指定，默认False
a = torch.randn(2,2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


梯度
因为out是一个scalar，out.backward()等于out.backward(torch.tensor(1))

In [8]:
out.backward()

In [9]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [10]:
#可以使用autograd做更多的操作
x = torch.randn(3,requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2
print(y)

tensor([ 619.6501, -916.8435,  476.8702], grad_fn=<MulBackward0>)


In [19]:
print(x.requires_grad)
print((x ** 2).requires_grad)
with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
