Tensors(张量)
tensors和numpy中的ndarrays类似，但在pytorch中tensors可以使用GPU进行计算

In [1]:
from __future__ import print_function
import torch

创建一个5x3矩阵，但未定义

In [3]:
x = torch.empty(5,3)
x

tensor([[-2.5560e+19,  3.0714e-41, -2.5112e+19],
        [ 3.0714e-41,  1.1210e-43,  0.0000e+00],
        [ 1.5695e-43,  0.0000e+00, -2.5367e+19],
        [ 3.0714e-41,  2.5223e-44,  0.0000e+00],
        [        nan,  3.8946e+21,  1.1578e+27]])

In [4]:
#随机初始化一个矩阵
x = torch.rand(5,3)
x

tensor([[0.0780, 0.9867, 0.6062],
        [0.2667, 0.1236, 0.9496],
        [0.6038, 0.6157, 0.6580],
        [0.7047, 0.9114, 0.0941],
        [0.1008, 0.7513, 0.7666]])

In [7]:
#创建一个0填充的矩阵，数据类型为long
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [8]:
#创建tensor并使用现有数据初始化
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [9]:
#根据现有的张量创建张量
x = x.new_ones(5,3,dtype=torch.double)#new_*方法创建对象
print(x)

x = torch.randn_like(x,dtype=torch.float)#覆盖dtype!
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.9049, -0.1802,  1.3264],
        [-0.0988,  1.8650,  0.1787],
        [ 0.3762, -0.0593, -1.3351],
        [ 0.3328, -0.4799, -1.8258],
        [ 1.2866, -0.2709, -2.1064]])


In [11]:
#获取size
print(x.size())

torch.Size([5, 3])


In [12]:
#进行加法运算
#加法1
y = torch.rand(5,3)
print(x + y)

tensor([[-0.3865,  0.1387,  1.5789],
        [ 0.2989,  2.1615,  1.0434],
        [ 0.4128,  0.1500, -0.6177],
        [ 0.3693, -0.0334, -0.8700],
        [ 1.4298, -0.1024, -1.6337]])


In [13]:
#加法2
print(torch.add(x,y))

tensor([[-0.3865,  0.1387,  1.5789],
        [ 0.2989,  2.1615,  1.0434],
        [ 0.4128,  0.1500, -0.6177],
        [ 0.3693, -0.0334, -0.8700],
        [ 1.4298, -0.1024, -1.6337]])


In [14]:
#提供输出tensor作为参数
result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[-0.3865,  0.1387,  1.5789],
        [ 0.2989,  2.1615,  1.0434],
        [ 0.4128,  0.1500, -0.6177],
        [ 0.3693, -0.0334, -0.8700],
        [ 1.4298, -0.1024, -1.6337]])


In [15]:
#替换
#adds x to y
y.add_(x)
print(y)

tensor([[-0.3865,  0.1387,  1.5789],
        [ 0.2989,  2.1615,  1.0434],
        [ 0.4128,  0.1500, -0.6177],
        [ 0.3693, -0.0334, -0.8700],
        [ 1.4298, -0.1024, -1.6337]])


In [16]:
#使用与numpy索引方式相同的操作来进行对张量的操作
print(x[:,1])

tensor([-0.1802,  1.8650, -0.0593, -0.4799, -0.2709])


In [17]:
#torch.view:可以改变张量的维度和大小
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [18]:
#只有一个元素的张量，可以使用.item()来得到python数据类型的数值
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.3398])
-0.3397812247276306


In [19]:
#torch tensor和numpy数组相互转换,共享底层内存地址
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [20]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [21]:
#观察numpy数组的值是如何改变的
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [22]:
#numpy数组转换成torch tensor
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [26]:
#CUDA张量
if torch.cuda.is_available():               #判断是否有cuda可以使用
    device = torch.device("cuda") 
    y = torch.ones_like(x,device=device)    #直接从GPU创建张量
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu",torch.double))